 #!/bin/sh
 
# MaMuT print radius annotation up/down counts
# 2019-2021 Martin H. Dominguez
# Gladstone Institutes

# Prints up and down counts for radius annotation files (CSV format: Annotation,Timepoint,Position_T,ID), as would be generated by MaMuT_dataset_dataset_export_radius_annotations.pl
# usage: bash MaMuT_radius_annotations_print_UpDown_counts.sh
 
 for file in *.txt; do
 echo $file
 cat $file | grep -c "Up"
 cat $file | grep -c "Down"
 done
